[harpocrates]
192.168.1.98 ansible_user=m3l6h
192.168.1.98 ansible_port=7272
192.168.1.98 ansible_ssh_private_key_file=~/.ssh/harpocrates_primary_ed25519_sk
192.168.1.98 ansible_python_interpreter=/usr/bin/python3.14
